FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY coqueiral_fastapi/ ./coqueiral_fastapi

ENV PYTHONPATH=/app

CMD ["uvicorn", "coqueiral_fastapi.app.auth_service.main:app", "--host", "0.0.0.0", "--port", "8000"]